name: Test Manylinux build

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    name:
      ${{ matrix.platform }}, Parser option ${{ matrix.xml_parser_option }},
      with namespaces ${{ matrix.with_namespace}}, strict includes ${{
      matrix.strict }}, with examples ${{ matrix.with_examples}}, package option
      ${{ matrix.package_option}}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]
        xml_parser_option: ["-DWITH_LIBXML"]
        with_namespace: ["True"]
        strict: ["True"]
        with_examples: ["True"]
        package_option: ["-DWITH_STABLE_PACKAGES=ON"]
        cpp_standard: [98]
        language_bindings:
          ["-DWITH_JAVA=True -DWITH_CSHARP=True -DWITH_PYTHON=True"]
    runs-on: ${{ matrix.platform }}
    container: quay.io/pypa/manylinux1_x86_64

    steps:
      - name: What OS is running
        run: |
          uname -a
          git --version
          git clone https://github.com/alessandrofelder/libsbml.git
          cmake --version
          mkdir build
          cd build
          cmake ../libsbml
          -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
          -DCMAKE_CXX_STANDARD=${{matrix.cpp_standard}} \
          -DWITH_CHECK=True \
          -DWITH_CPP_NAMESPACE=${{matrix.with_namespace}} \
          -DLIBSBML_USE_STRICT_INCLUDES=${{matrix.strict}} \
          -DWITH_EXAMPLES=${{matrix.with_examples}} \
          ${{matrix.package_option}} \
          ${{matrix.language_bindings}} \
          -DWITH_STATIC_RUNTIME=ON \
          -DPYTHON_USE_DYNAMIC_LOOKUP=ON

